name: debugger-action
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

     - name: Setup Debug Session
       uses: csexton/debugger-action@master
